# Generated by Django 4.0.4 on 2022-06-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='academic_council',
        ),
        migrations.DeleteModel(
            name='board_of_governors',
        ),
        migrations.DeleteModel(
            name='board_of_studies',
        ),
        migrations.DeleteModel(
            name='doct_ta',
        ),
        migrations.DeleteModel(
            name='finance_committee',
        ),
        migrations.DeleteModel(
            name='grad_ta',
        ),
        migrations.DeleteModel(
            name='iqac',
        ),
        migrations.DeleteModel(
            name='research_area',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='area_of_specialisation',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='number_of_doctorate_students_guided',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='number_of_graduate_students_guided',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='staffs',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
