# Generated by Django 4.0.4 on 2022-06-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0002_delete_academic_council_delete_board_of_governors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='session_year_id',
        ),
        migrations.AlterField(
            model_name='students',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
