# Generated by Django 4.0.4 on 2022-06-29 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0005_alter_students_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='doct_ta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('guide', models.TextField(default='', max_length=100)),
                ('area_of_work', models.TextField(max_length=1000)),
                ('year_of_registration', models.IntegerField(validators=[django.core.validators.MinValueValidator(2002), django.core.validators.MaxValueValidator(2022)])),
            ],
        ),
        migrations.CreateModel(
            name='grad_ta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('guide', models.TextField(default='', max_length=100)),
                ('specialization', models.TextField(max_length=1000)),
                ('year_of_registration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1999), django.core.validators.MaxValueValidator(2022)])),
            ],
        ),
    ]
