# Generated by Django 4.0.4 on 2022-06-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0007_grad_ta_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grad_ta',
            name='year_of_registration',
            field=models.IntegerField(),
        ),
    ]
