# Generated by Django 4.0.4 on 2022-06-29 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0008_alter_grad_ta_year_of_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grad_ta',
            name='year_of_registration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2002), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
