# Generated by Django 4.0.4 on 2022-06-29 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0010_doct_ta_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='research_area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year_completed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1999), django.core.validators.MaxValueValidator(2022)])),
                ('title', models.TextField(max_length=1000)),
                ('spron_auth', models.TextField(max_length=255)),
                ('cost', models.BigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
