# Generated by Django 4.0.4 on 2022-07-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0012_remove_staffs_address_staffs_area_of_specialisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='academic_council',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('position', models.TextField(max_length=255)),
                ('address', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='board_of_governors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('position', models.TextField(max_length=255)),
                ('address', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='board_of_studies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('position', models.TextField(max_length=255)),
                ('address', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='finance_committee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('position', models.TextField(max_length=255)),
                ('address', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='iqac',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('position', models.TextField(max_length=255)),
                ('address', models.CharField(max_length=600)),
            ],
        ),
    ]
