# Generated by Django 4.0.4 on 2022-07-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0013_academic_council_board_of_governors_board_of_studies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='committee_and_board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('position', models.TextField(max_length=255)),
                ('address', models.CharField(max_length=600)),
                ('committee', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='academic_council',
        ),
        migrations.DeleteModel(
            name='board_of_governors',
        ),
        migrations.DeleteModel(
            name='board_of_studies',
        ),
        migrations.DeleteModel(
            name='finance_committee',
        ),
        migrations.DeleteModel(
            name='iqac',
        ),
    ]
