# Generated by Django 4.0.4 on 2022-07-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0014_committee_and_board_delete_academic_council_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee_and_board',
            name='committee',
            field=models.CharField(max_length=255),
        ),
    ]
