# Generated by Django 4.0.4 on 2022-07-10 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0015_alter_committee_and_board_committee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('guide', models.TextField(default='', max_length=100)),
                ('area_of_work', models.TextField(max_length=1000)),
                ('year_of_registration', models.IntegerField(validators=[django.core.validators.MinValueValidator(2002), django.core.validators.MaxValueValidator(2022)])),
                ('type', models.CharField(max_length=255)),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accreditation_app.students')),
            ],
        ),
        migrations.RemoveField(
            model_name='grad_ta',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='doct_ta',
        ),
        migrations.DeleteModel(
            name='grad_ta',
        ),
    ]
