# Generated by Django 4.0.4 on 2022-07-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0016_ta_remove_grad_ta_student_id_delete_doct_ta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='guide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accreditation_app.staffs'),
        ),
    ]
