# Generated by Django 4.1.1 on 2022-09-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0019_remove_attendancereport_attendance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
