# Generated by Django 4.1.1 on 2022-11-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0020_alter_students_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='institute_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('address', models.TextField(default='')),
                ('emp', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pin', models.IntegerField()),
                ('website', models.CharField(max_length=400)),
                ('area', models.BigIntegerField(default=0)),
                ('builtup_area', models.BigIntegerField(default=0)),
                ('recognition_date', models.DateField()),
                ('institute_type', models.TextField()),
                ('institute_nature', models.TextField()),
                ('establishment_date', models.DateField()),
                ('mail_prefix', models.TextField()),
            ],
        ),
    ]
