# Generated by Django 4.1.1 on 2022-11-08 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0022_remove_institute_details_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhod',
            name='institute_to_belong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accreditation_app.institute_details'),
        ),
        migrations.AddField(
            model_name='committee_and_board',
            name='institute_to_belong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accreditation_app.institute_details'),
        ),
        migrations.AddField(
            model_name='research_area',
            name='institute_to_belong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accreditation_app.institute_details'),
        ),
        migrations.AddField(
            model_name='staffs',
            name='institute_to_belong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accreditation_app.institute_details'),
        ),
        migrations.AddField(
            model_name='students',
            name='institute_to_belong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accreditation_app.institute_details'),
        ),
    ]
