# Generated by Django 4.1.1 on 2022-11-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0023_adminhod_institute_to_belong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute_details',
            name='establishment_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='institute_details',
            name='recognition_date',
            field=models.DateField(default=''),
        ),
    ]
