# Generated by Django 4.1.1 on 2022-11-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0025_alter_institute_details_establishment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute_details',
            name='campus_type',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='institute_details',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='institute_details',
            name='institute_nature',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='institute_details',
            name='institute_type',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='institute_details',
            name='mail_prefix',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='institute_details',
            name='pin',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='institute_details',
            name='state',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='institute_details',
            name='website',
            field=models.CharField(default='', max_length=400),
        ),
    ]
