# Generated by Django 4.1.1 on 2022-11-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0026_institute_details_campus_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute_details',
            name='website',
            field=models.URLField(default='', max_length=400),
        ),
    ]
