# Generated by Django 4.1.1 on 2022-11-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0027_alter_institute_details_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.TextField(default='', max_length=50),
        ),
    ]
