# Generated by Django 4.1.1 on 2022-11-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0028_alter_students_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta',
            name='institute_to_belong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accreditation_app.institute_details'),
        ),
    ]
