# Generated by Django 4.1.1 on 2022-11-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0029_ta_institute_to_belong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'hod'), ('2', 'staff'), ('3', 'student')], default=1, max_length=10),
        ),
    ]
