# Generated by Django 4.1.1 on 2022-11-21 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0030_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField(default=0)),
                ('total_expense', models.BigIntegerField(default=0)),
                ('institute_to_belong', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accreditation_app.institute_details')),
            ],
        ),
    ]
