# Generated by Django 4.1.1 on 2022-12-13 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0031_expense_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenditure_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor', models.TextField(default='')),
                ('gstnum', models.TextField(default='', max_length=15)),
                ('fiscal_year', models.IntegerField(default=0)),
                ('units', models.BigIntegerField(default=0)),
                ('purpose', models.TextField(default='')),
                ('price_per_unit', models.BigIntegerField(default=0)),
                ('paymode', models.TextField(default='')),
                ('cheque_number', models.TextField(default='')),
                ('total_expense', models.BigIntegerField(default=0)),
                ('institute_to_belong', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accreditation_app.institute_details')),
                ('ordering_person', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accreditation_app.staffs')),
            ],
        ),
        migrations.DeleteModel(
            name='expense_details',
        ),
    ]
