# Generated by Django 4.1.1 on 2022-12-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0032_expenditure_details_delete_expense_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='revenue_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.TextField(default='')),
                ('fiscal_year', models.IntegerField(default=0)),
                ('purpose', models.TextField(default='')),
                ('paymode', models.TextField(default='')),
                ('cheque_number', models.TextField(default='')),
                ('total_revenue', models.BigIntegerField(default=0)),
                ('institute_to_belong', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accreditation_app.institute_details')),
            ],
        ),
    ]
