# Generated by Django 4.1.1 on 2023-04-19 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0033_revenue_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_area',
            name='year_completed',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1999), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AlterField(
            model_name='ta',
            name='year_of_registration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2002), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
