# Generated by Django 4.1.1 on 2023-07-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0035_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminhod',
            name='institute_to_belong',
        ),
        migrations.RemoveField(
            model_name='committee_and_board',
            name='institute_to_belong',
        ),
        migrations.RemoveField(
            model_name='expenditure_details',
            name='institute_to_belong',
        ),
        migrations.RemoveField(
            model_name='research_area',
            name='institute_to_belong',
        ),
        migrations.RemoveField(
            model_name='revenue_details',
            name='institute_to_belong',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='institute_to_belong',
        ),
        migrations.RemoveField(
            model_name='students',
            name='institute_to_belong',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='institute_to_belong',
        ),
    ]
