# Generated by Django 4.1.1 on 2023-08-19 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0036_remove_adminhod_institute_to_belong_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadedFilesHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filetype', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('whatUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
